name: Build

on:
  workflow_dispatch:
    inputs:
        Alpha:
          description: 'Alpha'
          required: false
          default: 'false'
        Premium:
          description: 'Premium'
          required: false
          default: 'false'
        Foss:
          description: 'Foss'
          required: false
          default: 'false'

jobs:
  build:
    name: "Build APKs"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source-next

    permissions:
      contents: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Fix Rust toolchain conflict
        run: |
          rustup update
          rustup component remove rust-std-aarch64-linux-android || true
          rustup target add aarch64-linux-android || true
          cargo clean || true
          rm -rf ~/.cargo/registry/cache ~/.cargo/git/db

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Decode store file
        env:
            STORE_FILE: ${{ secrets.STORE_FILE }}
            ENCODED_STRING: ${{ secrets.STORE_BASE64 }}
        run: echo $ENCODED_STRING | base64 -di > "./app/${STORE_FILE}"

      - name: Build with gradle
        id: gradle
        env:
          STORE_FILE: ${{ secrets.STORE_FILE }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          BUILD_ALPHA: ${{ github.event.inputs.Alpha }}
          BUILD_PREMIUM: ${{ github.event.inputs.Premium }}
          BUILD_FOSS: ${{ github.event.inputs.Foss }}
        run: |
          TASKS=""
          if [ ${BUILD_ALPHA} = 'true' ]; then
            TASKS="$TASKS assembleArm64-v8aAlphaRelease"
          fi
          if [ ${BUILD_PREMIUM} = 'true' ]; then
            TASKS="$TASKS assembleArm64-v8aPremiumRelease"
          fi
          if [ ${BUILD_FOSS} = 'true' ]; then
            TASKS="$TASKS assembleArm64-v8aFossRelease"
          fi
          if [ -z ${TASKS} ]; then
            TASKS="assembleDebug assembleRelease"
          fi
          ./gradlew $TASKS --daemon --parallel

      - name: Move APKs
        run: |
          ls -lh */build/outputs/apk/*/*/*.apk
          echo
          find . -type f -name *.apk -exec ls -lh {} \;
          find . -type f -name *.apk -exec mv {} . \;

      - name: Upload APKs
        uses: actions/upload-artifact@v7
        with:
          name: APKs
          path: '**/*.apk'
